version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: roomit-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: capstone
      MYSQL_USER: roomit
      MYSQL_PASSWORD: 1234
    ports:
      - "3331:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - roomit-network

volumes:
  mysql-data:

networks:
  roomit-network:
