spring:
  datasource:
    url: jdbc:mysql://localhost:3330/capstone?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root  # ← 네 워크벤치 접속 아이디
    password: 1234  # ← 네 비밀번호로 바꿔
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081  # 포트 충돌 방지
